apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: project-managment-api-deployment
  name: project-managment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-managment-api
  template:
    metadata:
      labels:
        app: project-managment-api
    spec:
      containers:
      - image: 710979589756.dkr.ecr.eu-north-1.amazonaws.com/projectmanagement:685ca952967e513a862eefea24b2a034ba30cfb8
        name: project-managment-api
        ports:
        - containerPort: 8000
      
