apiVersion: v1
kind: Service
metadata:
  name: project-management-api-service
spec:
  selector:
    app: project-managment-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
