# Generated by Django 4.0.2 on 2022-04-11 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examiner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examiners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=25)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.batch')),
            ],
            options={
                'db_table': 'groups',
                'unique_together': {('group_name', 'batch')},
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.student')),
            ],
            options={
                'unique_together': {('group', 'member')},
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'titles',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='SubmissionType',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'submission_types',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group')),
                ('sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.submissiontype')),
            ],
            options={
                'db_table': 'submissions',
            },
        ),
        migrations.CreateModel(
            name='StudentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255, null=True)),
                ('mark', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_evaluation', to='core.examiner')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_student', to='core.member')),
                ('submission_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_evaluation', to='core.submissiontype')),
            ],
            options={
                'db_table': 'student_evalaution',
            },
        ),
        migrations.AddField(
            model_name='examiner',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examiners', to='core.group'),
        ),
        migrations.CreateModel(
            name='TopProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.title')),
            ],
            options={
                'db_table': 'top_projects',
                'unique_together': {('title_name',)},
            },
        ),
        migrations.CreateModel(
            name='SubmissionDeadLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dead_line', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_deadline_batch', to='core.batch')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_type_deadline', to='core.submissiontype')),
            ],
            options={
                'db_table': 'submission_dead_lines',
                'unique_together': {('name', 'batch')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='examiner',
            unique_together={('group', 'examiner')},
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='core.batch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'batch')},
            },
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisors', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisors', to='core.group')),
            ],
            options={
                'unique_together': {('group', 'advisor')},
            },
        ),
    ]
