# Generated by Django 4.0.2 on 2022-04-03 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_group_member_examiner_advisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTitle',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='projecttitles', serialize=False, to='core.group')),
                ('title', models.CharField(max_length=25)),
                ('doc_path', models.CharField(blank=True, max_length=500)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
