# Generated by Django 4.0.4 on 2022-05-14 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220507_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=200)),
                ('title_description', models.TextField()),
                ('no', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')])),
                ('rejection_reason', models.CharField(default=None, max_length=1000)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_titles', to='core.group')),
            ],
            options={
                'unique_together': {('group', 'no')},
            },
        ),
        migrations.CreateModel(
            name='Semister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'semisters',
                'unique_together': {('name',)},
            },
        ),
        migrations.AlterUniqueTogether(
            name='coordinator',
            unique_together={('user', 'batch')},
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'titles',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='SubmissionType',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('max_mark', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('semister', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semisters', to='core.semister')),
            ],
            options={
                'db_table': 'submission_types',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='StudentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255, null=True)),
                ('mark', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_evaluation', to='core.examiner')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_student', to='core.member')),
                ('submission_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_evaluation', to='core.submissiontype')),
            ],
            options={
                'db_table': 'student_evalaution',
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.projecttitle')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voters',
                'unique_together': {('user_id',)},
            },
        ),
        migrations.CreateModel(
            name='TopProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_path', models.CharField(blank=True, max_length=500)),
                ('vote', models.IntegerField(default=0, null=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('is_approved', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_batch', to='core.batch')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_group', to='core.group')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_title', to='core.projecttitle')),
            ],
            options={
                'db_table': 'top_projects',
                'unique_together': {('batch', 'group')},
            },
        ),
        migrations.CreateModel(
            name='SubmissionDeadLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dead_line', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_deadline_batch', to='core.batch')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_type_deadline', to='core.submissiontype')),
            ],
            options={
                'db_table': 'submission_dead_lines',
                'unique_together': {('name', 'batch')},
            },
        ),
    ]
