# Generated by Django 4.0.4 on 2022-05-23 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220507_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=200)),
                ('title_description', models.TextField()),
                ('no', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')])),
                ('rejection_reason', models.CharField(default=None, max_length=1000)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_titles', to='core.group')),
            ],
            options={
                'db_table': 'project_title',
                'unique_together': {('group', 'no')},
            },
        ),
        migrations.AddField(
            model_name='submissiontype',
            name='max_mark',
            field=models.FloatField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='coordinator',
            unique_together={('user', 'batch')},
        ),
        migrations.CreateModel(
            name='Semister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'semisters',
                'unique_together': {('name',)},
            },
        ),
        migrations.AddField(
            model_name='submissiontype',
            name='semister',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semisters', to='core.semister'),
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.projecttitle')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voters',
                'unique_together': {('user_id',)},
            },
        ),
        migrations.CreateModel(
            name='TopProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_path', models.CharField(blank=True, max_length=500)),
                ('vote', models.IntegerField(default=0, null=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('is_approved', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_projects_batch', to='core.batch')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_projects_group', to='core.group')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_projects_title', to='core.projecttitle')),
            ],
            options={
                'db_table': 'top_projects',
                'unique_together': {('batch', 'title')},
            },
        ),
    ]
