# Generated by Django 4.0.4 on 2022-05-29 09:49

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_countmodel_titlesubmissiondeadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=core.models.submission_file_path)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_group', to='core.group')),
                ('submissionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_submission_type', to='core.submissiontype')),
            ],
            options={
                'unique_together': {('group', 'submissionType')},
            },
        ),
    ]
