# Generated by Django 4.0.2 on 2022-03-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_student_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='id',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='startDate',
        ),
        migrations.AddField(
            model_name='batch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='name',
            field=models.CharField(blank=True, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
