# Generated by Django 4.0.4 on 2022-06-21 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_numberofvoter_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberofvoter',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_voters', to='core.topproject'),
        ),
    ]
